export * from '~/components/templates/HomeTemplate'
export * from '~/components/templates/ArticleTemplate'
export * from '~/components/templates/ListTemplate'
export * from '~/components/templates/ProfileTemplate'
export * from '~/components/templates/ContactTemplate'
export * from '~/components/templates/AboutTemplate'
