export { default as Navigation } from '~/components/organisms/Navigation'
export { default as Mainvisual } from '~/components/organisms/Mainvisual'
export { default as Footer } from '~/components/organisms/Footer'
export { default as Title } from '~/components/organisms/Title'
export { default as Content } from '~/components/organisms/Content'
export { default as List } from '~/components/organisms/List'
export { default as Profile } from '~/components/organisms/Profile'
export { default as SkilList } from '~/components/organisms/SkilList'
